export default [
  {
    id: 0,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/0mNSixnpY8PwD5bSDNwde8O3MdVAszvS.jpeg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 1,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/EPWj1pM-qi2llu-PUSQAI8sBdh8Dnjbv.jpeg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 2,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/KnJyr9e7BFMEOztI9ZqDms9vpc3VLZMV.jpeg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 3,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/s_Iazm4nr4_Dwbm5ZnpwpkRO6_6EyRUQ.jpg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 4,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/pr5svItBQNHioRIFRd5ib62FlF1_9oTM.jpg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 5,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/HxH1u-CxPw_jblruS1JQ3U3ZN3UPHI1r.jpg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 6,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/5fX2SjYRN7qXJipRGYIJ2W8y1s9eEd3T.jpeg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
  {
    id: 7,
    artist: "",
    description: "",
    src: "https://tdart-tatto.s3.amazonaws.com/53cKsHTDmV22ya77a8s9CYkcHy7EiLcW.jpg",
    width: 768,
    height: 468,
    alt: "The Inked Clown",
  },
];
